/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CoinId = IDL.Text;
export const AddHoldingRequest = IDL.Record({
  'quantity' : IDL.Float64,
  'priceAtTrade' : IDL.Float64,
  'coinId' : CoinId,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const RawJson = IDL.Text;
export const Timestamp = IDL.Int;
export const HoldingView = IDL.Record({
  'totalCost' : IDL.Float64,
  'updatedAt' : Timestamp,
  'quantity' : IDL.Float64,
  'costBasis' : IDL.Float64,
  'coinId' : CoinId,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const UpdateHoldingRequest = IDL.Record({
  'quantity' : IDL.Float64,
  'costBasis' : IDL.Float64,
  'coinId' : CoinId,
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addHolding' : IDL.Func([AddHoldingRequest], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCoinMetadata' : IDL.Func([IDL.Text], [RawJson], []),
  'getCoinPriceHistory' : IDL.Func([IDL.Text], [RawJson], []),
  'getCurrentPrices' : IDL.Func([IDL.Text], [RawJson], []),
  'getFearGreedIndex' : IDL.Func([], [RawJson], []),
  'getHolding' : IDL.Func([CoinId], [IDL.Opt(HoldingView)], ['query']),
  'getHoldings' : IDL.Func([], [IDL.Vec(HoldingView)], ['query']),
  'getTop100Coins' : IDL.Func([], [RawJson], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeHolding' : IDL.Func([CoinId], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateHolding' : IDL.Func([UpdateHoldingRequest], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CoinId = IDL.Text;
  const AddHoldingRequest = IDL.Record({
    'quantity' : IDL.Float64,
    'priceAtTrade' : IDL.Float64,
    'coinId' : CoinId,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const RawJson = IDL.Text;
  const Timestamp = IDL.Int;
  const HoldingView = IDL.Record({
    'totalCost' : IDL.Float64,
    'updatedAt' : Timestamp,
    'quantity' : IDL.Float64,
    'costBasis' : IDL.Float64,
    'coinId' : CoinId,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const UpdateHoldingRequest = IDL.Record({
    'quantity' : IDL.Float64,
    'costBasis' : IDL.Float64,
    'coinId' : CoinId,
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addHolding' : IDL.Func([AddHoldingRequest], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCoinMetadata' : IDL.Func([IDL.Text], [RawJson], []),
    'getCoinPriceHistory' : IDL.Func([IDL.Text], [RawJson], []),
    'getCurrentPrices' : IDL.Func([IDL.Text], [RawJson], []),
    'getFearGreedIndex' : IDL.Func([], [RawJson], []),
    'getHolding' : IDL.Func([CoinId], [IDL.Opt(HoldingView)], ['query']),
    'getHoldings' : IDL.Func([], [IDL.Vec(HoldingView)], ['query']),
    'getTop100Coins' : IDL.Func([], [RawJson], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeHolding' : IDL.Func([CoinId], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateHolding' : IDL.Func([UpdateHoldingRequest], [], []),
  });
};

export const init = ({ IDL }) => { return []; };