/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AddHoldingRequest {
  'quantity' : number,
  'priceAtTrade' : number,
  'coinId' : CoinId,
}
export type CoinId = string;
export interface HoldingView {
  'totalCost' : number,
  'updatedAt' : Timestamp,
  'quantity' : number,
  'costBasis' : number,
  'coinId' : CoinId,
}
export type RawJson = string;
export type Timestamp = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UpdateHoldingRequest {
  'quantity' : number,
  'costBasis' : number,
  'coinId' : CoinId,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addHolding' : ActorMethod<[AddHoldingRequest], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCoinMetadata' : ActorMethod<[string], RawJson>,
  'getCoinPriceHistory' : ActorMethod<[string], RawJson>,
  'getCurrentPrices' : ActorMethod<[string], RawJson>,
  'getFearGreedIndex' : ActorMethod<[], RawJson>,
  'getHolding' : ActorMethod<[CoinId], [] | [HoldingView]>,
  'getHoldings' : ActorMethod<[], Array<HoldingView>>,
  'getTop100Coins' : ActorMethod<[], RawJson>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeHolding' : ActorMethod<[CoinId], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateHolding' : ActorMethod<[UpdateHoldingRequest], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];